# -*- coding: utf-8 -*-
"""diabetes_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_9zFHtOODX8aPTdYOVBI66vcCbUOmjJ_
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

data = load_diabetes()

data

df = pd.DataFrame(data.data, columns=data.feature_names)

df

df['target'] = data.target

df

x = df.drop('target', axis=1).values

x

y = df['target'].values

y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train

y_train

x_test

y_test

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

y_pred

y_test

from sklearn.metrics import mean_squared_error

print (mean_squared_error(y_test, y_pred))



from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print(f"R-squared (R2 Score): {r2:.2f}")

"""The R-squared score is another important metric for regression models. It ranges from 0 to 1, where:

*   **0** indicates that the model explains none of the variability of the response data around its mean.
*   **1** indicates that the model explains all the variability of the response data around its mean.

After running the cell above, we can interpret if your model is trained well based on both MSE and R-squared values.
"""